name: kraken_forge
channels:
  - pytorch
  - fastai
  - conda-forge
  - defaults
dependencies:
  - python==3.6
  - python-bidi
  - lxml
  - future
  - regex
  - requests
  - click>=7.0
  - numpy
  - pillow
  - scipy
  - protobuf>=3.0.0
  - jinja2
  - torchvision-nightly-cpu
  - pytorch-nightly-cpu
  - pip:
    - coremltools
    - git+https://github.com/mittagessen/kraken.git@master
