name: kraken
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python>=3.6
  - python-bidi
  - lxml
  - future
  - regex
  - requests
  - click>=7.0
  - numpy
  - pillow>=6.2.2
  - scipy
  - protobuf>=3.0
  - jinja2
  - cpuonly
  - torchvision
  - pytorch==1.4.0
  - jsonschema
  - scikit-image
  - shapely
  - pip
  - pyvips
  - imagemagick<7.0.9
  - pip:
    - coremltools>=3.3
    - git+https://github.com/mittagessen/kraken.git@master
