name: kraken
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python>=3.6
  - python-bidi
  - lxml
  - future
  - regex
  - requests
  - click>=7.0
  - numpy
  - pillow
  - scipy
  - protobuf>=3.0
  - jinja2
  - cpuonly
  - torchvision
  - pytorch==1.3.0
  - jsonschema
  - scikit-image
  - shapely
  - pip
  - wand
  - pip:
    - coremltools>=3.3
    - git+https://github.com/mittagessen/kraken.git@master
