package:
  name: kraken
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..

requirements:
  build:
     - python
     - setuptools
     - pbr
  run:
     - python
     - python-bidi==0.4.2
     - lxml==4.8.0
     - regex==2021.11.2
     - requests==2.27.1
     - click>=7.0
     - numpy==1.19.5
     - pillow>=6.2.2
     - scipy==1.7.3
     - protobuf>=3.0
     - jinja2==3.0.2
     - conda-forge::torchvision==0.11.3
     - conda-forge::pytorch>=1.10
     - cudatoolkit>=9.2
     - jsonschema==3.2.0
     - scikit-image==0.19.2
     - shapely==1.7.1
     - pyvips==2.1.15
     - imagemagick>=7.1.0
     - coremltools>=3.3
     - libffi # [osx]
     - pyarrow==4.0.1
     - conda-forge::pytorch-lightning==1.5.10
     - albumentations==1.0.3
     - rich==10.16.2
about:
  home: http://kraken.re
  license: Apache License
  summary: 'OCR/HTR engine for all the languages'
